project_id = "pcwyueagjkabmieoccew"
[functions.ai-product-draft]
verify_jwt = false

[functions.ai-image-studio]
verify_jwt = false

[functions.ai-image-upscale]
verify_jwt = false

[functions.ai-team-bio]
verify_jwt = false
